.TH HR 1 "April 16, 2016"
.SH NAME
hcat \- Highlighted cat
.SH SYNOPSIS
.B hcat
.RI file
.RI [ file ]
.SH DESCRIPTION
Concatenate the input files to the standard output like cat. If the language of the input is detected, the output is highlighted.
.SH SEE ALSO
pygmentize(1) is the tool used for colorize the output.
.SH COPYRIGHT
This software is free software and is released under the GNU GPL version 3  or upper <http://gnu.org/licenses/gpl.html>
