#! /usr/bin/env python
#
# this script is provided under GPL v3 or upper

import sys

import pygments

from pygments.lexers import get_lexer_for_filename
from pygments import highlight
from pygments.formatters import Terminal256Formatter
from pygments.lexers import guess_lexer


def display(data, lexer):
    print highlight(data, lexer, Terminal256Formatter())



if __name__ == '__main__':
    numbers_of_files = len(sys.argv) - 1
    if numbers_of_files:
        OFFSET = 1
        for i in range(numbers_of_files):
            filename = sys.argv[i + OFFSET]
            with open(filename) as f:
                data = f.read()
            try:
                lexer = get_lexer_for_filename(filename)
            except pygments.util.ClassNotFound:
                lexer = guess_lexer(data)
            display(data, lexer)
    else:
        f = sys.stdin
        data = f.read()
        lexer = guess_lexer(data)
        display(data, lexer)

