.TH HR 1 "April 16, 2016"
.SH NAME
hcat \- cat command with highlight
.SH SYNOPSIS
.B hcat
.RI file
.RI [ file ]
.SH DESCRIPTION
Concatenate the input files to the standard output like cat. If the format of the content is detected, the output is colored.
.SH SEE ALSO
pygmentize(1) is the tool used for colorize the output.
